### ISSUE TITLE
Error 

### ISSUE THREAD

**Issue by Aryanstha** [whoami-anoint/ipfinder#1]
print("The IP for " + url + " is " + socket.gethostbyname(url))
socket.gaierror: [Errno 11001] getaddrinfo failed

**Comment by whoami-anoint** [comment]
**This error appears when the internet connection with Fusion 360 is unstable.** 
_You may fixed this error with below solution:_
[Click on Solution](https://knowledge.autodesk.com/support/3ds-max/troubleshooting/caas/sfdcarticles/sfdcarticles/Fusion-360-won-t-launch-error-Errno-11001-in-installation-log.html)
